### PR TITLE
Bug fix for command 'requirement_add'

### LINKED ISSUE #113: RequirementAddCommand: Unable to add more than 1 module code to a requirement category
The current implementation of the 'requirement_add' command has a bug where no more than 1 module code can be added to a requirement category. 

* The desired behavior of the command is where the module code would be successfully added into the specified requirement category.

* However, the current behavior is that the application throws an error: `UnsupportedOperationException` and the module code is not added into the specified requirement category.

The bug was caused by not using a new `Set<Code>` variable, in the logic flow when a module code is added to a requirement category. 

Let's fix this existing bug by changing the logic flow of how a module code is added to a requirement category.

### PR DESCRIPTION
**Pull request by chyeo**
resolves #113 
The implementation of the `requirement_add` command has a bug where no 
more than one module code can be added to a requirement category.

The bug was caused by not creating a new `Set<Code>` variable whenever a
module code is added to a requirement category.

To fix this bug, we create a new `Set<Code>` containing both the 
existing module codes and the module code to be added. We also update 
`RequirementAddCommandParser` to pass the only data parsed instead of 
creating a new `RequirementCategory` instance.

Let's fix the bug and close issue #113 using the methods described above
and cascade the changes to the affected classes. To prevent further 
regression bugs, let's also add in additional unit tests to ensure the 
desired behavior of the `requirement_add` command.

* [1/6] [requirement: update logic of new command and checks](https://github.com/CS2113-AY1819S2-T09-1/main/pull/112/commits/4f2a462cd41aba408cf58c5e31c704deee791e94)
* [2/6] [Update to files to reference updated methods](https://github.com/CS2113-AY1819S2-T09-1/main/pull/112/commits/ab6a8cd593885fdb811cfcca29131fca43339bcb)
* [3/6] [RequirementAddCommand: update methods and to receive data parsed](https://github.com/CS2113-AY1819S2-T09-1/main/pull/112/commits/f50bf6133fd68ac714417e30eba85c11b8632e0b)
* [4/6] [AddCommandTest: update to reference updated methods](https://github.com/CS2113-AY1819S2-T09-1/main/pull/112/commits/e7d783021db8d3e6b2585a50576887c21dc5bb84)
* [5/6] [test: update on test data generated](https://github.com/CS2113-AY1819S2-T09-1/main/pull/112/commits/3b83bef87a86c97d49c0edaa5f67ab7a1425b482)
* [6/6] [RequirementAddCommandTest: update to add in new test cases](https://github.com/CS2113-AY1819S2-T09-1/main/pull/112/commits/e799553f47ab3cc20498973acca73c450db6d6e5)

### CODE REVIEW

File: src/main/java/seedu/address/model/requirement/RequirementCategory.java [hunk 1]
```diff
@@ -63,6 +65,51 @@ public boolean isSameRequirementCategory(RequirementCategory otherRequirementCat
                 && otherRequirementCategory.getName().equals(getName());
     }
 
+    /**
+     * Returns true if the list contains an equivalent requirement as the given argument.
+     */
+    public boolean hasModuleCodeAdded(RequirementCategory currentRequirementCategory,
```
Comment (Creastery) [inline src/main/java/seedu/address/model/requirement/RequirementCategory.java]: Rename `hasModuleCodeAdded` -> `hasModuleCode`

File: src/main/java/seedu/address/model/requirement/RequirementCategory.java [hunk 2]
```diff
@@ -63,6 +65,51 @@ public boolean isSameRequirementCategory(RequirementCategory otherRequirementCat
...
+            Set<Code> codeSet) {
+        Set<Code> currentList = currentRequirementCategory.getCodeList();
```
Comment (Creastery) [inline src/main/java/seedu/address/model/requirement/RequirementCategory.java]: Let's avoid using `xyzList` when we are actually trying to work with `Set` instead of `List`.
Please refactor:
* `currentList` -> `currentSet`
* `RequirementCategory#getCodeList()` -> `RequirementCategory#getCodeSet()`

File: src/main/java/seedu/address/model/requirement/RequirementCategory.java [hunk 3]
```diff
@@ -63,6 +65,51 @@ public boolean isSameRequirementCategory(RequirementCategory otherRequirementCat
...
+
+        for (Code existingCode : currentList) {
+            for (Code newCode : codeSet) {
+                if (existingCode.value.equals(newCode.value)) {
```
Comment (Creastery) [inline src/main/java/seedu/address/model/requirement/RequirementCategory.java]: You should not be checking the raw `value` directly!
Instead, `Code#equals()` should be used here.

Anyway, this nested for loop can be simplified using `.stream().anyMatch(...)`.

File: src/main/java/seedu/address/model/requirement/RequirementCategory.java [hunk 4]
```diff
@@ -63,6 +65,51 @@ public boolean isSameRequirementCategory(RequirementCategory otherRequirementCat
...
+                }
+            }
+        }
+        return false;
+    }
+
+    /**
+     * Returns the a new codeSet of module codes.
+     */
+    public Set<Code> newCodeSet(Set<Code> currentCodeSet, Set<Code> inputCodeSet) {
```
Comment (Creastery) [inline src/main/java/seedu/address/model/requirement/RequirementCategory.java]: Having a `newCodeSet(...)` method in `RequirementCategory` makes no sense at all, as `RequirementCategory` is not an object builder utility class!

Given the simplicity of this method's objectives, I think this method can be removed completely.

File: src/main/java/seedu/address/model/requirement/RequirementCategory.java [hunk 5]
```diff
@@ -63,6 +65,51 @@ public boolean isSameRequirementCategory(RequirementCategory otherRequirementCat
...
+        Set<Code> newCodeSet = new HashSet<>(currentCodeSet);
+        newCodeSet.addAll(inputCodeSet);
+
+        return newCodeSet;
+    }
+
+    /**
+     * Returns the total amount of credits in the new codeSet.
+     */
+    public Integer getNewCreditsAmount(ObservableList<Module> moduleList, Set<Code> codeSet) {
```
Comment (Creastery) [inline src/main/java/seedu/address/model/requirement/RequirementCategory.java]: This method is implemented as an extension to your feature, and does not contribute in fixing the bug mentioned.
Please avoid mixing features within PRs, as this makes reviewing extremely.
Having said that, please remove this method from this PR. Thank you.

File: src/main/java/seedu/address/model/requirement/UniqueRequirementCategoryList.java [hunk 6]
```diff
@@ -42,21 +38,22 @@
     /**
      * Returns true if the list contains an equivalent requirement as the given argument.
```
Comment (Creastery) [inline src/main/java/seedu/address/model/requirement/UniqueRequirementCategoryList.java]: Can you update the JavaDoc for `contains(...)`? 
The argument is not a `RequirementCategory `, but instead, it is a `Name`.

File: src/main/java/seedu/address/model/requirement/UniqueRequirementCategoryList.java [hunk 7]
```diff
@@ -42,21 +38,22 @@
...
      */
-    public boolean contains(RequirementCategory toCheck) {
+    public boolean contains(Name toCheck) {
```
Comment (Creastery) [inline src/main/java/seedu/address/model/requirement/UniqueRequirementCategoryList.java:41]: I see value in keeping the original implementation of the `contains(...)` method.

Let's keep both the original implementation and your amended implementation of `contains(...)`.
(i.e. overloading `contains(...)` method)

File: src/main/java/seedu/address/model/requirement/UniqueRequirementCategoryList.java [hunk 8]
```diff
@@ -42,21 +38,22 @@
...
-        return internalList.stream().anyMatch(toCheck::isSameRequirementCategory);
+        return internalList.stream().anyMatch((requirementCategory) -> requirementCategory.getName().equals(toCheck));
     }
 
     /**
-     * Returns location of the requirementCategory in the internalList.
+     * Returns a RequirementCategory object of the requirementCategory in the internalList.
      */
-    public int location(RequirementCategory toCheck) {
+    public RequirementCategory getRequirementCategoryName(Name toCheck) {
```
Comment (Creastery) [inline src/main/java/seedu/address/model/requirement/UniqueRequirementCategoryList.java]: `getRequirementCategoryName` can mean that you want to get the `Name` of a `RequirementCategory`.
Please rename `getRequirementCategoryName(...)` to `getRequirementCategory`.

File: src/main/java/seedu/address/model/requirement/UniqueRequirementCategoryList.java [hunk 9]
```diff
@@ -68,7 +65,7 @@ public int location(RequirementCategory toCheck) {
      */
     public void add(RequirementCategory toAdd) {
         requireNonNull(toAdd);
-        if (contains(toAdd)) {
+        if (contains(toAdd.getName())) {
```
Comment (Creastery) [inline src/main/java/seedu/address/model/requirement/UniqueRequirementCategoryList.java]: Revert this changes in view of above comments.

File: src/main/java/seedu/address/model/requirement/UniqueRequirementCategoryList.java [hunk 10]
```diff
@@ -78,65 +75,14 @@ public void add(RequirementCategory toAdd) {
...
-        Set<Code> inputList = toAdd.getCodeList();
-
-        for (Code currentCode : currentListInRequirementCategory) {
-            inputList.add(currentCode);
-        }
-
-        RequirementCategory edited =
-                new RequirementCategory(internalList.get(location).getName(), internalList.get(location).getCredits(),
-                        inputList);
+    public void addModuleToRequirementCategory(RequirementCategory currentRequirementCategory,
```
Comment (Creastery) [inline src/main/java/seedu/address/model/requirement/UniqueRequirementCategoryList.java]: This method is completely redundant. `setRequirementCategory` already does exactly what this method does!

File: src/main/java/seedu/address/model/requirement/UniqueRequirementCategoryList.java [hunk 11]
```diff
@@ -196,20 +143,17 @@ public void setRequirementCategories(List<RequirementCategory> requirementCatego
         return internalUnmodifiableList;
     }
 
-    @Override
-    public Iterator<RequirementCategory> iterator() {
+    @Override public Iterator<RequirementCategory> iterator() {
```
Comment (Creastery) [inline src/main/java/seedu/address/model/requirement/UniqueRequirementCategoryList.java]: Avoid unnecessary changes.
Let's separate `@Override` annotations and method declarations with a new line.

File: src/main/java/seedu/address/model/requirement/UniqueRequirementCategoryList.java [hunk 12]
```diff
@@ -196,20 +143,17 @@ public void setRequirementCategories(List<RequirementCategory> requirementCatego
...
         return internalList.iterator();
     }
 
-    @Override
-    public boolean equals(Object other) {
+    @Override public boolean equals(Object other) {
```
Comment (Creastery) [inline src/main/java/seedu/address/model/requirement/UniqueRequirementCategoryList.java]: Avoid unnecessary changes.
Let's separate `@Override` annotations and method declarations with a new line.

File: src/main/java/seedu/address/model/requirement/UniqueRequirementCategoryList.java [hunk 13]
```diff
@@ -196,20 +143,17 @@ public void setRequirementCategories(List<RequirementCategory> requirementCatego
...
         return other == this // short circuit if same object
                 || (other instanceof UniqueRequirementCategoryList // instanceof handles nulls
                 && internalList.equals(((UniqueRequirementCategoryList) other).internalList));
     }
 
-    @Override
-    public int hashCode() {
+    @Override public int hashCode() {
```
Comment (Creastery) [inline src/main/java/seedu/address/model/requirement/UniqueRequirementCategoryList.java]: Avoid unnecessary changes.
Let's separate `@Override` annotations and method declarations with a new line.

File: src/main/java/seedu/address/model/requirement/UniqueRequirementCategoryList.java [hunk 14]
```diff
@@ -42,21 +38,22 @@
...
+    public RequirementCategory getRequirementCategoryName(Name toCheck) {
         requireNonNull(toCheck);
-        int location = 0;
+        RequirementCategory location = null;
+
         for (int i = 0; i < internalList.size(); i++) {
-            if (toCheck.getName().equals(internalList.get(i).getName())) {
-                location = i;
-                i = internalList.size();
+            if (toCheck.equals(internalList.get(i).getName())) {
```
Comment (Creastery) [inline src/main/java/seedu/address/model/requirement/UniqueRequirementCategoryList.java]: Think you can simplify the loop using streams and filter.

File: src/main/java/seedu/address/model/AddressBook.java [hunk 15]
```diff
@@ -139,13 +140,22 @@ public void removeModule(Module key) {
...
+    }
+
     /**
      * Returns true if an requirement with the same identity as {@code requirement} exists in the
      * requirement.
      */
-    public boolean hasRequirementCategory(RequirementCategory requirementCategory) {
-        requireNonNull(requirementCategory);
-        return requirementCategories.contains(requirementCategory);
+    public RequirementCategory getRequirementCategoryName(Name requirementCategoryName) {
```
Comment (Creastery) [inline src/main/java/seedu/address/model/AddressBook.java]: Please rename `getRequirementCategoryName(...)` -> `getRequirementCategory(...)`

File: src/main/java/seedu/address/model/AddressBook.java [hunk 16]
```diff
@@ -181,28 +191,11 @@ public void removeRequirementCategory(RequirementCategory key) {
...
-
-    /**
-     * Returns false if a module with the same identity as {@code requirementCategory} does not exists
-     * in the current moduleList.
-     */
-    //TODO refine this method to use methods in PR#91
-    public boolean doesModuleExistInApplication(RequirementCategory requirementCategory, Model model) {
-        requireNonNull(requirementCategory);
-        return requirementCategories.doesModuleExistInApplication(requirementCategory, model);
+    public void addModuleToRequirementCategory(RequirementCategory currentRequirementCategory,
```
Comment (Creastery) [inline src/main/java/seedu/address/model/AddressBook.java]: As mentioned previously, this method is redundant, and hence should be removed.

File: src/main/java/seedu/address/model/Model.java [hunk 17]
```diff
@@ -227,16 +228,16 @@
...
+    boolean hasRequirementCategory(Name requirementCategoryName);
 
     /**
-     * Deletes the given requirement.
-     * The requirement must exist in the address book.
+     * Returns true if a requirement with the code as {@code requirement} exists in the
+     * requirement list.
      */
-    void deleteRequirementCategory(RequirementCategory target);
+    RequirementCategory getRequirementCategoryName(Name requirementCategoryName);
```
Comment (Creastery) [inline src/main/java/seedu/address/model/Model.java]: Please rename `getRequirementCategoryName(...)` -> `getRequirementCategory(...)`

File: src/main/java/seedu/address/model/Model.java [hunk 18]
```diff
@@ -257,19 +258,8 @@
...
-     * requirement category to be added to.
-     */
-    boolean isModuleInRequirementCategory(RequirementCategory requirementCategory);
-
-    /**
-     * Returns false if a module with the same identity as {@code requirementCategory} does not exists
-     * in the current moduleList.
-     */
-    boolean doesModuleExistInApplication(RequirementCategory requirementCategory, Model model);
+    void addModuleToRequirementCategory(RequirementCategory currentRequirementCategory,
```
Comment (Creastery) [inline src/main/java/seedu/address/model/Model.java]: Please remove this redundant method (as discussed above).

File: src/main/java/seedu/address/logic/commands/RequirementAddCommand.java [hunk 19]
```diff
@@ -16,57 +23,65 @@
...
 
-    public static final String MESSAGE_SUCCESS = "Module added to %1$s ";
+    public static final String MESSAGE_SUCCESS = "Module added to requirement category: %1$s ";
     public static final String MESSAGE_REQUIREMENT_CATEGORY_DOES_NOT_EXIST =
             "The requirement category: %1$s does not exist";
-    public static final String MESSAGE_MODULE_DOES_NOT_EXIST =
-            "The module code does not exists in the module list";
-    public static final String MESSAGE_DUPLICATE_MODULE_IN_REQUIREMENT_CATEGORY =
+    public static final String MESSAGE_NONEXISTENT_CODE =
+            "The module does not exists in the module list";
```
Comment (Creastery) [inline src/main/java/seedu/address/logic/commands/RequirementAddCommand.java]: You need to explain the _why_ more.

Example:
"The module **to be added to the requirement category** does not exists in the module list!"

File: src/main/java/seedu/address/logic/commands/RequirementAddCommand.java [hunk 20]
```diff
@@ -16,57 +23,65 @@
...
+    public static final String MESSAGE_DUPLICATE_CODE =
             "The module has already been added to %1$s ";
 
-    private final RequirementCategory toAdd;
+    private final Name requirementCategoryName;
+    private final Set<Code> codeSet = new HashSet<>();
```
Comment (Creastery) [inline src/main/java/seedu/address/logic/commands/RequirementAddCommand.java]: To be consistent with the rest of the `XYZCommand` classes, you should name this variable as `toAdd`.

File: src/main/java/seedu/address/logic/commands/RequirementAddCommand.java [hunk 21]
```diff
@@ -16,57 +23,65 @@
...
-    public static final String MESSAGE_MODULE_DOES_NOT_EXIST =
-            "The module code does not exists in the module list";
-    public static final String MESSAGE_DUPLICATE_MODULE_IN_REQUIREMENT_CATEGORY =
+    public static final String MESSAGE_NONEXISTENT_CODE =
+            "The module does not exists in the module list";
+    public static final String MESSAGE_DUPLICATE_CODE =
             "The module has already been added to %1$s ";
 
-    private final RequirementCategory toAdd;
+    private final Name requirementCategoryName;
```
Comment (Creastery) [inline src/main/java/seedu/address/logic/commands/RequirementAddCommand.java]: To be consistent with the rest of the `XYZCommand` classes, you should name this variable as `tofind`.

File: src/main/java/seedu/address/logic/commands/RequirementAddCommand.java [hunk 22]
```diff
@@ -16,57 +23,65 @@
...
+            + "Parameters: "
+            + PREFIX_NAME + "NAME "
+            + "[" + PREFIX_CODE + "CODE]...\n"
+            + "Example: " + COMMAND_WORD + " "
+            + PREFIX_NAME + "IT Professionalism "
+            + PREFIX_CODE + "IS4231 ";
 
-    public static final String MESSAGE_SUCCESS = "Module added to %1$s ";
+    public static final String MESSAGE_SUCCESS = "Module added to requirement category: %1$s ";
     public static final String MESSAGE_REQUIREMENT_CATEGORY_DOES_NOT_EXIST =
```
Comment (Creastery) [inline src/main/java/seedu/address/logic/commands/RequirementAddCommand.java]: `MESSAGE_REQUIREMENT_CATEGORY_DOES_NOT_EXIST` -> `MESSAGE_NONEXISTENT_REQUIREMENT_CATEGORY`.

File: src/main/java/seedu/address/logic/commands/RequirementAddCommand.java [hunk 23]
```diff
@@ -16,57 +23,65 @@
...
+        if (currentRequirementCategory.hasModuleCodeAdded(currentRequirementCategory, codeSet)) {
             throw new CommandException(
-                    String.format(MESSAGE_DUPLICATE_MODULE_IN_REQUIREMENT_CATEGORY, toAdd.getName()));
+                    String.format(MESSAGE_DUPLICATE_CODE, requirementCategoryName));
         }
 
-        model.addModuleToRequirementCategory(toAdd);
-        model.commitAddressBook();
-        return new CommandResult(String.format(MESSAGE_SUCCESS, toAdd.getName()));
+        Set<Code> newCodeSet = currentRequirementCategory.newCodeSet(currentRequirementCategory.getCodeList(), codeSet);
```
Comment (Creastery) [inline src/main/java/seedu/address/logic/commands/RequirementAddCommand.java]: Should be:
```java
Set<Code> newCodeSet = new Set<>(currentRequirementCategory.getCodeSet());
newCodeSet.addAll(toAdd);
```

File: src/main/java/seedu/address/logic/commands/RequirementAddCommand.java [hunk 24]
```diff
@@ -16,57 +23,65 @@
...
+        Credits newCredit = new Credits(currentRequirementCategory.getNewCreditsAmount(
+                model.getFilteredModuleList(), newCodeSet).toString());
 
+        RequirementCategory editedRequirementCategory = new RequirementCategory(
+                requirementCategoryName, newCredit, newCodeSet);
```
Comment (Creastery) [inline src/main/java/seedu/address/logic/commands/RequirementAddCommand.java]: This seems to imply that `Credits` of `RequirementCategory` is the "current progress".
But, in actual fact, it is the number of modular credits required to satisfy the requirement set out in this `RequirementCategory`!

If you want to track the current `Credits`, you should be modifying the model for `RequirementCategory` to add a new attribute.

File: src/main/java/seedu/address/logic/commands/RequirementAddCommand.java [hunk 25]
```diff
@@ -16,57 +23,65 @@
...
+        model.addModuleToRequirementCategory(currentRequirementCategory, editedRequirementCategory);
+        model.commitAddressBook();
+        return new CommandResult(String.format(MESSAGE_SUCCESS, requirementCategoryName));
     }
 
-    @Override public boolean equals(Object other) {
-        return other == this // short circuit if same object
-                || (other instanceof RequirementAddCommand // instanceof handles nulls
-                && toAdd.equals(((RequirementAddCommand) other).toAdd));
```
Comment (Creastery) [inline src/main/java/seedu/address/logic/commands/RequirementAddCommand.java]: Why is the `equals(...)` method removed?

File: src/test/java/seedu/address/testutil/RequirementCategoryBuilder.java [hunk 26]
```diff
@@ -45,11 +45,11 @@ public RequirementCategoryBuilder withName(String name) {
     }
 
     /**
-     * Parses the {@code codeList} into a {@code Set<Code>} and set it to the {@code RequirementCategory} that we are
+     * Parses the {@code codeSet} into a {@code Set<Code>} and set it to the {@code RequirementCategory} that we are
      * building.
      */
-    public RequirementCategoryBuilder withCodes(Set<Code> codeList) {
-        this.codeList = SampleDataUtil.getCodeSet();
+    public RequirementCategoryBuilder withCodes(String ... codes) {
```
Comment (Creastery) [inline src/test/java/seedu/address/testutil/RequirementCategoryBuilder.java]: Any particular reason for this change in method signature?
By the way, please remove the space before `...`

**Review by Creastery — CHANGES_REQUESTED** [review]

File: src/test/java/seedu/address/testutil/RequirementCategoryBuilder.java (hunk 26 above)
Comment (chyeo) [reply src/test/java/seedu/address/testutil/RequirementCategoryBuilder.java]: This is to match the `public static Set<Code> getCodeSet(String... strings)` method in `SampleDataUtil.java`

File: src/main/java/seedu/address/model/requirement/UniqueRequirementCategoryList.java [hunk 27]
```diff
@@ -153,7 +98,8 @@ public void setRequirementCategory(RequirementCategory target, RequirementCatego
             throw new RequirementCategoryNotFoundException();
         }
 
-        if (!target.isSameRequirementCategory(editedRequirementCategory) && contains(editedRequirementCategory)) {
+        if (!target.isSameRequirementCategory(editedRequirementCategory)
+                && contains(editedRequirementCategory)) {
```
Comment (Creastery) [inline src/main/java/seedu/address/model/requirement/UniqueRequirementCategoryList.java]: There is no need to put the conditions on two lines when it can fit within a single line!

File: src/main/java/seedu/address/model/requirement/UniqueRequirementCategoryList.java [hunk 28]
```diff
@@ -40,26 +38,37 @@
...
-        int location = 0;
-        for (int i = 0; i < internalList.size(); i++) {
-            if (toCheck.getName().equals(internalList.get(i).getName())) {
-                location = i;
-                i = internalList.size();
-            }
+
+        ArrayList<RequirementCategory> result = internalList.stream().filter(
+            requirementCategory -> requirementCategory.getName().equals(toCheck))
+            .collect(Collectors.toCollection(ArrayList:: new));
```
Comment (Creastery) [inline src/main/java/seedu/address/model/requirement/UniqueRequirementCategoryList.java]: Collecting the results to an `ArrayList` just to return the first filtered value (if present) is an overkill.
You could have simply simply returned:
```java
internalList.stream()
        .filter(requirementCategory -> requirementCategory.getNames().equals(toCheck))
        .findFirst()
        .orElse(null);
```

File: src/main/java/seedu/address/model/requirement/RequirementCategory.java [hunk 29]
```diff
@@ -63,6 +63,15 @@ public boolean isSameRequirementCategory(RequirementCategory otherRequirementCat
                 && otherRequirementCategory.getName().equals(getName());
     }
 
+    /**
+     * Returns true if the current codeSet contains an equivalent code in the parameter toCheck
+     */
+    public boolean hasModuleCode(RequirementCategory currentRequirementCategory, Set<Code> toCheck) {
```
Comment (Creastery) [inline src/main/java/seedu/address/model/requirement/RequirementCategory.java]: Why do you need to pass `RequirementCategory ` as an argument to this method? 
This method is an instance method!

File: src/main/java/seedu/address/storage/JsonSerializableRequirementCategoryList.java [hunk 30]
```diff
@@ -55,7 +55,7 @@ public JsonSerializableRequirementCategoryList(ReadOnlyAddressBook source) {
         AddressBook requirementCategoryList = new AddressBook();
         for (JsonAdaptedRequirementCategoryList jsonAdaptedRequirementCategoryList : requirementCategories) {
             RequirementCategory requirementCategory = jsonAdaptedRequirementCategoryList.toModelType();
-            if (requirementCategoryList.hasRequirementCategory(requirementCategory)) {
+            if (requirementCategoryList.hasRequirementCategory(requirementCategory.getName())) {
```
Comment (Creastery) [inline src/main/java/seedu/address/storage/JsonSerializableRequirementCategoryList.java]: Why lookup the object in the list by name when you already have the object reference?

File: src/test/java/seedu/address/logic/commands/RequirementAddCommandTest.java [hunk 31]
```diff
@@ -40,16 +38,32 @@
 
     @Test public void constructor_nullModule_throwsNullPointerException() {
         thrown.expect(NullPointerException.class);
-        new RequirementAddCommand(null);
+        new RequirementAddCommand(null, null);
     }
 
-    @Test public void execute_moduleToBeAddedDoesNotExist_throwsCommandException() {
+    @Test public void execute_requirementCategoryDoesNotExist_throwsCommandException() {
```
Comment (Creastery) [inline src/test/java/seedu/address/logic/commands/RequirementAddCommandTest.java]: Can we standardise the naming to match `MESSAGE_NONEXISTENT_REQUIREMENT_CATEGORY` please?

File: src/test/java/seedu/address/logic/commands/RequirementAddCommandTest.java [hunk 32]
```diff
@@ -40,16 +38,32 @@
...
+        codeList.clear();
+        Name requirementCategoryName = new Name("DOES NOT EXIST");
```
Comment (Creastery) [inline src/test/java/seedu/address/logic/commands/RequirementAddCommandTest.java]: See above comment.

File: src/test/java/seedu/address/logic/commands/RequirementAddCommandTest.java [hunk 33]
```diff
@@ -40,16 +38,32 @@
...
+        assertCommandFailure(new RequirementAddCommand(requirementCategoryName, codeList), model, commandHistory,
+                String.format(RequirementAddCommand.MESSAGE_NONEXISTENT_REQUIREMENT_CATEGORY,
+                        requirementCategoryName));
+    }
+
+    @Test public void execute_moduleCodeToBeAddedDoesNotExist_throwsCommandException() {
```
Comment (Creastery) [inline src/test/java/seedu/address/logic/commands/RequirementAddCommandTest.java]: See above comment.

File: src/test/java/seedu/address/logic/commands/RequirementAddCommandTest.java [hunk 34]
```diff
@@ -40,16 +38,32 @@
...
-        RequirementCategory requirementCategory =
-                new RequirementCategory(new Name("Computing Foundation"), new Credits("0"), codeList);
-        assertCommandFailure(new RequirementAddCommand(requirementCategory), model, commandHistory,
-                RequirementAddCommand.MESSAGE_MODULE_DOES_NOT_EXIST);
+        Name requirementCategoryName = new Name("Computing Foundation");
+        assertCommandFailure(new RequirementAddCommand(requirementCategoryName, codeList), model, commandHistory,
+                RequirementAddCommand.MESSAGE_NONEXISTENT_CODE);
+    }
+
+    @Test public void execute_moduleCodeToBeAddedAlreadyExistInRequirementCategory_throwsCommandException() {
```
Comment (Creastery) [inline src/test/java/seedu/address/logic/commands/RequirementAddCommandTest.java]: Can we standardise the naming to match `MESSAGE_DUPLICATE_CODE` please?

File: src/main/java/seedu/address/logic/commands/RequirementAddCommand.java [hunk 35]
```diff
@@ -16,57 +22,71 @@
...
+            throw new CommandException(
+                    String.format(MESSAGE_NONEXISTENT_REQUIREMENT_CATEGORY, toFind));
         }
 
-        if (!model.doesModuleExistInApplication(toAdd, model)) {
-            throw new CommandException(MESSAGE_MODULE_DOES_NOT_EXIST);
+        for (Code code : toAdd) {
+            if (!model.hasModuleCode(code)) {
+                throw new CommandException(MESSAGE_NONEXISTENT_CODE);
+            }
```
Comment (Creastery) [inline src/main/java/seedu/address/logic/commands/RequirementAddCommand.java]: This loop can be simplified to an if statement as such:
```java
if (toAdd.stream().anyMatch(code -> model.hasModuleCode(code) == false)) {
    throw new CommandException(MESSAGE_NONEXISTENT_CODE);
}
```

**Review by Creastery — CHANGES_REQUESTED** [review]

File: src/main/java/seedu/address/logic/commands/RequirementAddCommand.java [hunk 36]
```diff
@@ -16,57 +22,69 @@
...
     }
 
     @Override public CommandResult execute(Model model, CommandHistory history) throws CommandException {
         requireNonNull(model);
 
-        if (!model.hasRequirementCategory(toAdd)) {
-            throw new CommandException(String.format(MESSAGE_REQUIREMENT_CATEGORY_DOES_NOT_EXIST, toAdd.getName()));
+        RequirementCategory currentRequirementCategory = model.getRequirementCategory(toFind);
+
+        if (isNull(currentRequirementCategory)) {
```
Comment (Creastery) [inline src/main/java/seedu/address/logic/commands/RequirementAddCommand.java]: This should have been `currentRequirementCategory == null`.
Don't abuse `Objects.isNull`!
The documentation at [Objects.isNull](https://docs.oracle.com/javase/9/docs/api/java/util/Objects.html#isNull-java.lang.Object-) mentions the API note:
```
This method exists to be used as a Predicate, filter(Objects::isNull)
```

File: src/main/java/seedu/address/model/requirement/RequirementCategory.java [hunk 37]
```diff
@@ -63,6 +63,14 @@ public boolean isSameRequirementCategory(RequirementCategory otherRequirementCat
                 && otherRequirementCategory.getName().equals(getName());
     }
 
+    /**
+     * Returns true if the current codeSet contains an equivalent code in the parameter toCheck
+     */
+    public boolean hasModuleCode(Set<Code> toCheck) {
+        return (getCodeSet().stream().anyMatch((current) -> getCodeSet().containsAll(toCheck)));
```
Comment (Creastery) [inline src/main/java/seedu/address/model/requirement/RequirementCategory.java]: This is incorrect.
What you are trying to do is to determine if any `Code` in `toCheck` is already present in `codeSet`.
But instead, what's done here was:
For all elements of `getCodeSet()`, check if `getCodeSet()` contains all elements of `toCheck`

This should be:
```java
public boolean hasModuleCode(Set<Code> codeSetToCheck) {
    return codeSetToCheck.stream().anyMatch(codeToCheck -> codeSet.contains(codeToCheck));
}
```

Please update the comments to reflect this accordingly as well.

Comment (Creastery) [reply src/main/java/seedu/address/model/requirement/RequirementCategory.java]: Few things you should note as well:
1. Avoid name like `current` (too vague; not descriptive enough)
2. Avoid using getter methods (i.e. `getCodeSet()`) within the class (you have access to private class attributes!)
3. Let's stick to no parenthesis for single parameter for lambda expressions (i.e. remove `()` around `codeToCheck`)

**Review by Creastery — CHANGES_REQUESTED** [review]

File: src/main/java/seedu/address/logic/commands/RequirementAddCommand.java [hunk 38]
```diff
@@ -16,57 +21,69 @@
...
+        model.commitAddressBook();
+        return new CommandResult(String.format(MESSAGE_SUCCESS, toFind));
     }
 
-    @Override public boolean equals(Object other) {
+    @Override
+    public boolean equals(Object other) {
         return other == this // short circuit if same object
                 || (other instanceof RequirementAddCommand // instanceof handles nulls
-                && toAdd.equals(((RequirementAddCommand) other).toAdd));
```
Comment (Creastery) [inline src/main/java/seedu/address/logic/commands/RequirementAddCommand.java]: You need to keep this deleted line too!

File: src/main/java/seedu/address/model/requirement/UniqueRequirementCategoryList.java [hunk 39]
```diff
@@ -40,26 +36,31 @@
...
+        return internalList.stream().map(RequirementCategory::getName).anyMatch(toCheck::equals);
+    }
+
+    /**
+     * Returns true if the list contains an equivalent RequirementCategory as the given argument.
      */
     public boolean contains(RequirementCategory toCheck) {
         requireNonNull(toCheck);
-        return internalList.stream().anyMatch(toCheck::isSameRequirementCategory);
+        return internalList.stream().anyMatch(toCheck::equals);
```
Comment (Creastery) [inline src/main/java/seedu/address/model/requirement/UniqueRequirementCategoryList.java]: Please keep the original `toCheck::isSameRequirementCategory`.
The `equals()` checks are a lot stricter.

**Review by Creastery — CHANGES_REQUESTED** [review]

**Review by Creastery — APPROVED** [review]
