### PR TITLE
planner_add: command enhancement

### LINKED ISSUE #166: Improving `planner_add` to handle co-requisites
Currently, `planner_add` command does not handle co-requisites. Hence, users may miss out the co-requisites of certain modules and fail to plan well. Furthermore, a potential issue also needs to be fixed. (There lacks an error handling for null pointer returned.)

Hence, let's update `planner_add` to handle the co-requisites so that when the module(s) is added, other modules with the module's co-requisite will be added too. Also, let's add in an error-checking mechanism to detect null pointer returned and throw an exception accordingly.

### PR DESCRIPTION
**Pull request by WendyBaiYunwei**
Closes #166 

Current `planner_add` command does not support addition of Co-requisites.
Meanwhile, there lacks a check for null.

These problems respectively makes adding of Co-requisites troublesome, and the programme not secure enough.

Let's make `planner_add` support Co-requisites and add in a check for a `DegreePlanner` object that may return null when a `DegreePlanner` with a certain `Year` and `Semester` is not found.

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/PlannerAddCommand.java [hunk 1]
```diff
@@ -1,6 +1,7 @@
 package seedu.address.logic.commands;
 
 import static java.util.Objects.requireNonNull;
+
```
Comment (Creastery) [inline src/main/java/seedu/address/logic/commands/PlannerAddCommand.java]: Remove unnecessary addition of newline.

File: src/main/java/seedu/address/logic/commands/PlannerAddCommand.java [hunk 2]
```diff
@@ -37,10 +40,13 @@
             + PREFIX_CODE + "CS2113T "
             + PREFIX_CODE + "CS2100";
 
-    public static final String MESSAGE_SUCCESS = "Added new module(s) to year %1$s semester %2$s of"
+    private static final String MESSAGE_SUCCESS = "Added new module(s) to year %1$s semester %2$s of"
             + " the degree plan: \n%3$s";
-    public static final String MESSAGE_DUPLICATE_CODE = "The module(s) %1$s already exist in the degree plan.";
-    public static final String MESSAGE_MODULE_DOES_NOT_EXIST = "The module(s) %1$s do not exist in the module list.";
```
Comment (Creastery) [inline src/main/java/seedu/address/logic/commands/PlannerAddCommand.java]: Why are all the messages made `private`?

File: src/main/java/seedu/address/logic/commands/PlannerAddCommand.java [hunk 3]
```diff
@@ -37,10 +40,13 @@
...
+    private static final String COREQ_MESSAGE_SUCCESS = "\nCo-requisite(s) added:\n%1$s";
```
Comment (Creastery) [inline src/main/java/seedu/address/logic/commands/PlannerAddCommand.java]: This should be within `MESSAGE_SUCCESS`. 
When no co-requisites are added, simply supply "None" to the format string.

File: src/main/java/seedu/address/logic/commands/PlannerAddCommand.java [hunk 4]
```diff
@@ -37,10 +40,13 @@
...
+    private static final String MESSAGE_DUPLICATE_CODE = "The module(s) %1$s already exists in the degree plan.";
+    private static final String MESSAGE_MODULE_DOES_NOT_EXIST = "The module(s) %1$s does not exist in the module list.";
+    private static final String MESSAGE_PLAN_DOES_NOT_EXIST = "The degree plan of year %1$s and semester"
+            + "%2$s does not exist.";
```
Comment (Creastery) [inline src/main/java/seedu/address/logic/commands/PlannerAddCommand.java]: Let's keep variables more concise and consistent.
`MESSAGE_NONEXISTENT_MODULES` and `MESSAGE_NONEXISTENT_DEGREE_PLANNER` are more intuitive.

File: src/main/java/seedu/address/logic/commands/PlannerAddCommand.java [hunk 5]
```diff
@@ -79,13 +87,31 @@ public CommandResult execute(Model model, CommandHistory history) throws Command
             throw new CommandException(String.format(MESSAGE_MODULE_DOES_NOT_EXIST, nonExistentModuleCodes));
         }
 
-        Set<Code> newCodeSet = new HashSet<>(selectedDegreePlanner.getCodes());
-        newCodeSet.addAll(codesToAdd);
+        Set<Code> selectedCodeSet = new HashSet<>(selectedDegreePlanner.getCodes());
+        Set<Code> coreqAdded = new HashSet<>();
+        selectedCodeSet.addAll(codesToAdd);
+        for (Code codeToAdd :codesToAdd) {
```
Comment (Creastery) [inline src/main/java/seedu/address/logic/commands/PlannerAddCommand.java]: Please add space after `:`.

File: src/main/java/seedu/address/logic/commands/PlannerAddCommand.java [hunk 6]
```diff
@@ -79,13 +87,31 @@ public CommandResult execute(Model model, CommandHistory history) throws Command
...
+            selectedCodeSet.add(codeToAdd);
+            //adds Co-requisite(s)
+            Module module = model.getModuleByCode(codeToAdd);
+            if (module.getCorequisites().size() > 0) {
```
Comment (Creastery) [inline src/main/java/seedu/address/logic/commands/PlannerAddCommand.java]: This if statement check is redundant since `addAll()` does nothing on an empty set anyways.

File: src/main/java/seedu/address/logic/commands/PlannerAddCommand.java [hunk 7]
```diff
@@ -79,13 +87,31 @@ public CommandResult execute(Model model, CommandHistory history) throws Command
...
+                coreqAdded.addAll(module.getCorequisites());
+                selectedCodeSet.addAll(module.getCorequisites());
+            }
+        }
+
+        coreqAdded.removeAll(codesToAdd);
```
Comment (Creastery) [inline src/main/java/seedu/address/logic/commands/PlannerAddCommand.java]: Isn't `coreqAdded` going to be equivalent to `selectedCodeSet.removeAll(codesToAdd)`?
If so, you could just do:
```java
Set<Code> coreqAdded = new HashSet<>(selectedCodeSet);
coreqAdded.removeAll(codesToAdd);
```

**Review by Creastery — CHANGES_REQUESTED** [review]

File: src/main/java/seedu/address/logic/commands/PlannerAddCommand.java (hunk 2 above)
Comment (WendyBaiYunwei) [reply src/main/java/seedu/address/logic/commands/PlannerAddCommand.java]: I have changed the messages back to public. 
But I changed them to private initially because I didn't think they were necessary to be public, since they are used inside the command class only. As we should keep the access modifier as private as possible, I changed them to private.

Comment (Creastery) [reply src/main/java/seedu/address/logic/commands/PlannerAddCommand.java]: I see. Do note that these message variables need to have `public` access modifiers so that you can refer to them in your unit tests!

Comment (WendyBaiYunwei) [reply src/main/java/seedu/address/logic/commands/PlannerAddCommand.java]: Anyway, I changed them back to private still because at least for now, these 3 messages will not be used elsewhere. Please just inform me if it is necessary to change back.

Comment (Creastery) [reply src/main/java/seedu/address/logic/commands/PlannerAddCommand.java]: I think you can set the all the messages as `public`, since you will need to create unit tests to test the logic involving the excluded messages sooner or later.

Comment (WendyBaiYunwei) [reply src/main/java/seedu/address/logic/commands/PlannerAddCommand.java]: Somehow missed out your comment. I have changed them back. I got something urgent on now and cannot double check again. The tag will still be ongoing. If you feel that the changes meet the review requirement, please directly help me merge. If not, I will come back and double check again. please ignore this message if you have no time now.

File: src/main/java/seedu/address/logic/commands/PlannerAddCommand.java (hunk 7 above)
Comment (WendyBaiYunwei) [reply src/main/java/seedu/address/logic/commands/PlannerAddCommand.java]: Sorry after changing I realised that perhaps you misunderstood the code. selectedCodeSet contains all the codes in the selected degree planner. When directly adding in all the selectedCodeSet, all the codes that are not Co-req themselves will be added in as well, which is not what we want.

Comment (Creastery) [reply src/main/java/seedu/address/logic/commands/PlannerAddCommand.java]: Oh okay. In that case, then you can simplify:

https://github.com/CS2113-AY1819S2-T09-1/main/blob/7a97f009b683f2a443190981801685769f8e3886/src/main/java/seedu/address/logic/commands/PlannerAddCommand.java#L90-L103

into:

```java
Set<Code> selectedCodeSet = new HashSet<>(selectedDegreePlanner.getCodes());
selectedCodeSet.addAll(codesToAdd);
codesToAdd.stream().map(model::getModuleByCode).map(Module::getCorequisites).forEach(selectedCodeSet::addAll);

Set<Code> coreqAdded = new HashSet<>(selectedCodeSet);
coreqAdded.removeAll(codesToAdd);
```

File: src/main/java/seedu/address/logic/commands/PlannerAddCommand.java [hunk 8]
```diff
@@ -76,16 +82,31 @@ public CommandResult execute(Model model, CommandHistory history) throws Command
...
 
-        Set<Code> newCodeSet = new HashSet<>(selectedDegreePlanner.getCodes());
-        newCodeSet.addAll(codesToAdd);
+        Set<Code> coreqAdded = new HashSet<>(selectedCodeSet);
+        coreqAdded.removeAll(codesToAdd);
 
-        DegreePlanner editedDegreePlanner = new DegreePlanner(yearToAddTo, semesterToAddTo, newCodeSet);
+        DegreePlanner editedDegreePlanner = new DegreePlanner(yearToAddTo, semesterToAddTo, selectedCodeSet);
         model.setDegreePlanner(selectedDegreePlanner, editedDegreePlanner);
         model.commitAddressBook();
```
Comment (Creastery) [inline src/main/java/seedu/address/logic/commands/PlannerAddCommand.java]: You are updating only 1 degree planner here.
If the co-requisites you are adding over to this year & semester already exists in other years & semesters, there will be duplicate entries since the existing `DegreePlanner` for the other years & semesters are not updated.

**Review by Creastery — CHANGES_REQUESTED** [review]

File: src/main/java/seedu/address/logic/commands/PlannerAddCommand.java (hunk 8 above)
Comment (WendyBaiYunwei) [reply src/main/java/seedu/address/logic/commands/PlannerAddCommand.java]: Upon reviewing the code just now, I also realised the same problem. To resolve the issue, I threw a command exception and asked the users to move/remove the code(s) involved in order to proceed.

**Comment by WendyBaiYunwei** [comment]
The code for dealing with coreqs left out is maintained. though its function will be invisible in the current version, it can help with future modification of the application.

File: src/main/java/pwe/planner/logic/commands/PlannerAddCommand.java [hunk 9]
```diff
@@ -39,9 +41,14 @@
...
 
     public static final String MESSAGE_SUCCESS = "Added new module(s) to year %1$s semester %2$s of"
-            + " the degree plan: \n%3$s";
-    public static final String MESSAGE_DUPLICATE_CODE = "The module(s) %1$s already exist in the degree plan.";
-    public static final String MESSAGE_MODULE_DOES_NOT_EXIST = "The module(s) %1$s do not exist in the module list.";
+            + " the degree plan: \n%3$s\nCo-requisite(s) added:\n%4$s";
+    public static final String MESSAGE_DUPLICATE_CODE = "The module(s) %1$s already exists in the degree plan.";
+    public static final String MESSAGE_INVALID_COREQ = "The Co-requisite(s) %1$s of module(s) %2$s already exists"
+            + " in a different year and semester of the degree plan.\nModules that are Co-requisites to each other"
+            + " have to be in the same year and semester of the degree plan.";
```
Comment (Creastery) [inline src/main/java/pwe/planner/logic/commands/PlannerAddCommand.java]: `Co-requisites(s)` should be in lowercase.
`Modules that are Co-requisites to each other have to..` should be `Co-requisites modules have to...`

File: src/main/java/pwe/planner/logic/commands/PlannerAddCommand.java [hunk 10]
```diff
@@ -39,9 +41,14 @@
...
+    public static final String MESSAGE_NONEXISTENT_MODULES = "The module(s) %1$s does not exist in the module list.";
+    public static final String MESSAGE_NONEXISTENT_DEGREE_PLANNER = "The degree plan of year %1$s and semester"
+            + "%2$s does not exist.";
```
Comment (Creastery) [inline src/main/java/pwe/planner/logic/commands/PlannerAddCommand.java]: Should be:
```
Year %1$s Semester %2$s does not exists in the degree plan!
```

File: src/main/java/pwe/planner/logic/commands/PlannerAddCommand.java [hunk 11]
```diff
@@ -51,7 +58,6 @@
      */
     public PlannerAddCommand(Year year, Semester semester, Set<Code> codes) {
         requireAllNonNull(year, semester, codes);
-
```
Comment (Creastery) [inline src/main/java/pwe/planner/logic/commands/PlannerAddCommand.java]: Please add back the line here.
The line is used to separate pre-condition(s) from the remaining code.

File: src/test/java/pwe/planner/logic/parser/PlannerAddCommandParserTest.java [hunk 12]
```diff
@@ -0,0 +1,105 @@
...
+        assertParseFailure(parser, " " + PREFIX_YEAR + "1 " + PREFIX_SEMESTER + "% "
+                + PREFIX_CODE + "CS1010", Semester.MESSAGE_SEMESTER_CONSTRAINTS);
+
+        // invalid code
+        assertParseFailure(parser, " " + PREFIX_YEAR + "1 " + PREFIX_SEMESTER + "1 "
+                + PREFIX_CODE + "INVALID", Code.MESSAGE_CONSTRAINTS);
+
+        // invalid code
+        assertParseFailure(parser, " " + PREFIX_YEAR + "1 " + PREFIX_SEMESTER + "1 "
+                + PREFIX_CODE + null, Code.MESSAGE_CONSTRAINTS);
```
Comment (Creastery) [inline src/test/java/pwe/planner/logic/parser/PlannerAddCommandParserTest.java]: This test doesn't make sense.

**Review by Creastery — CHANGES_REQUESTED** [review]

File: src/main/java/pwe/planner/logic/commands/PlannerAddCommand.java [hunk 13]
```diff
@@ -63,29 +70,69 @@ public CommandResult execute(Model model, CommandHistory history) throws Command
...
+        if (duplicatePlannerCodes.size() > 0) {
+            throw new CommandException(String.format(MESSAGE_DUPLICATE_CODE, duplicatePlannerCodeString));
         }
 
-        Set<Code> nonExistentModuleCodes = codesToAdd.stream().filter(code -> !model.hasModuleCode(code))
-                .collect(Collectors.toSet());
+        Set<Code> nonExistentModuleCodes = codesToAdd.stream()
+                .filter(codesToCheck -> !model.hasModuleCode(codesToCheck)).collect(Collectors.toSet());
+        String nonExistentModuleString = nonExistentModuleCodes.stream().map(Code::toString)
+                .collect(Collectors.joining(", "));
```
Comment (Creastery) [inline src/main/java/pwe/planner/logic/commands/PlannerAddCommand.java]: This should be declared within the `if` statement.

File: src/main/java/pwe/planner/logic/commands/PlannerAddCommand.java [hunk 14]
```diff
@@ -63,29 +70,69 @@ public CommandResult execute(Model model, CommandHistory history) throws Command
...
+        Set<Code> duplicatePlannerCodes = codesToAdd.stream().filter(codesToCheck -> model.getApplication()
                 .getDegreePlannerList().stream().map(DegreePlanner::getCodes)
-                .anyMatch(codes -> codes.contains(code))).collect(Collectors.toSet());
-        if (existingPlannerCodes.size() > 0) {
-            throw new CommandException(String.format(MESSAGE_DUPLICATE_CODE, existingPlannerCodes));
+                .anyMatch(selectedPlannerCodes -> selectedPlannerCodes.contains(codesToCheck)))
+                .collect(Collectors.toSet());
+        // Converts a set to a string to remove the brackets of set.
+        String duplicatePlannerCodeString = duplicatePlannerCodes.stream().map(Code::toString)
+                .collect(Collectors.joining(", "));
```
Comment (Creastery) [inline src/main/java/pwe/planner/logic/commands/PlannerAddCommand.java]: This should be declared within the `if` statement.

File: src/main/java/pwe/planner/logic/commands/PlannerAddCommand.java [hunk 15]
```diff
@@ -63,29 +70,69 @@ public CommandResult execute(Model model, CommandHistory history) throws Command
...
+            // Returns the relevant duplicate co-requisite(s) in the entire degree plan.
+            Set<Code> duplicateCoreqs = module.getCorequisites().stream().filter(coreqToCheck -> model.getApplication()
+                    .getDegreePlannerList().stream().map(DegreePlanner::getCodes)
+                    .anyMatch(selectedPlannerCodes -> selectedPlannerCodes.contains(coreqToCheck)))
+                    .collect(Collectors.toSet());
+            Set<Code> invalidDuplicateCoreqs = new HashSet<>(duplicateCoreqs);
+            // Returns the invalid duplicate co-requisite(s) that exists in a different section of the degree plan.
+            invalidDuplicateCoreqs.removeAll(selectedDegreePlanner.getCodes());
+            if (invalidDuplicateCoreqs.size() > 0) {
+                throw new CommandException(String.format(MESSAGE_INVALID_COREQ, invalidDuplicateCoreqs, codesToAdd));
```
Comment (Creastery) [inline src/main/java/pwe/planner/logic/commands/PlannerAddCommand.java]: You're lacking `.stream().map(Code::toString).collect(Collectors.joining(", "))` for `invalidDuplicateCoreqs` and `codesToAdd` here.

**Review by Creastery — CHANGES_REQUESTED** [review]

**Review by Creastery — APPROVED** [review]
LGTM. Approving and merging.
